// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVDZLqqUpODzEJUS5gZWpS7MMppb_yTds',
    appId: '1:797418934455:web:d332dfb017eb94021c3d32',
    messagingSenderId: '797418934455',
    projectId: 'citazioni-libri',
    authDomain: 'citazioni-libri.firebaseapp.com',
    storageBucket: 'citazioni-libri.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsCY3GqYXgst_V2im5_Ystr5SplAApVzM',
    appId: '1:797418934455:android:bdb3e152b71989561c3d32',
    messagingSenderId: '797418934455',
    projectId: 'citazioni-libri',
    storageBucket: 'citazioni-libri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfpyF8wzHoQg_h-liniCWluQ_o9u18eBo',
    appId: '1:797418934455:ios:1a9e4db11e0b791e1c3d32',
    messagingSenderId: '797418934455',
    projectId: 'citazioni-libri',
    storageBucket: 'citazioni-libri.appspot.com',
    iosClientId: '797418934455-3lipanv86oki6lb2lo3fgfps0pvng0da.apps.googleusercontent.com',
    iosBundleId: 'com.example.cite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfpyF8wzHoQg_h-liniCWluQ_o9u18eBo',
    appId: '1:797418934455:ios:235e995562aabf161c3d32',
    messagingSenderId: '797418934455',
    projectId: 'citazioni-libri',
    storageBucket: 'citazioni-libri.appspot.com',
    iosClientId: '797418934455-pjvu72gt9ba7utnuddvn3frd6nb4s84c.apps.googleusercontent.com',
    iosBundleId: 'com.example.cite.RunnerTests',
  );
}
